version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: notifications_postgres
    restart: always
    environment:
      POSTGRES_DB: notifications_db
      POSTGRES_USER: notifications_user
      POSTGRES_PASSWORD: notifications_password
    ports:
      - "5892:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local